# Generated by Django 4.1.5 on 2023-01-26 15:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("endpoints", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="endpoint",
            unique_together={("url", "user")},
        ),
    ]
