# Generated by Django 4.1.5 on 2023-01-26 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("endpoints", "0002_alter_endpoint_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="healthCheckRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=10)),
                ("sends_at", models.DateTimeField()),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="endpoints.endpoint",
                    ),
                ),
            ],
        ),
    ]
