# Generated by Django 4.1.5 on 2023-01-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthcheckrequest",
            name="sends_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
